In [2]:
import rqdatac
rqdatac.init()
rqdatac.get_live_ticks(order_book_ids=['10002726'],start_dt='20210309094000',end_dt='20210309094002')

ValueError: username/password/addr or uri expected

In [3]:
import pandas as pd

pdf = pd.read_csv('tick_data_multi.csv')
pdf

,trading_date,open,last,high,low,prev_close,volume,total_turnover,limit_up,limit_down,...,a3_v,a4_v,a5_v,b1_v,b2_v,b3_v,b4_v,b5_v,change_rate,num_trades
0,2022-11-02,0.00,13.86,0.00,0.00,13.86,0.0,0.000000e+00,15.25,12.47,...,0.0,0.0,0.0,7100.0,1800.0,0.0,0.0,0.0,0.000000,0.0
1,2022-11-02,0.00,13.86,0.00,0.00,13.86,0.0,0.000000e+00,15.25,12.47,...,0.0,0.0,0.0,52100.0,0.0,0.0,0.0,0.0,0.000000,0.0
2,2022-11-02,0.00,13.86,0.00,0.00,13.86,0.0,0.000000e+00,15.25,12.47,...,0.0,0.0,0.0,52200.0,0.0,0.0,0.0,0.0,0.000000,0.0
3,2022-11-02,0.00,13.86,0.00,0.00,13.86,0.0,0.000000e+00,15.25,12.47,...,0.0,0.0,0.0,79300.0,9400.0,0.0,0.0,0.0,0.000000,0.0
4,2022-11-02,0.00,13.86,0.00,0.00,13.86,0.0,0.000000e+00,15.25,12.47,...,0.0,0.0,0.0,80600.0,8100.0,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9652,2022-11-02,10.61,10.62,10.68,10.48,10.67,129144598.0,1.365547e+09,11.74,9.60,...,0.0,0.0,0.0,922301.0,269699.0,0.0,0.0,0.0,-0.004686,77900.0
9653,2022-11-02,10.61,10.62,10.68,10.48,10.67,129144598.0,1.365547e+09,11.74,9.60,...,0.0,0.0,0.0,945701.0,304999.0,0.0,0.0,0.0,-0.004686,77900.0
9654,2022-11-02,10.61,10.62,10.68,10.48,10.67,129144598.0,1.365547e+09,11.74,9.60,...,0.0,0.0,0.0,992501.0,397099.0,0.0,0.0,0.0,-0.004686,77900.0
9655,2022-11-02,10.61,10.62,10.68,10.48,10.67,129144598.0,1.365547e+09,11.74,9.60,...,0.0,0.0,0.0,1083720.0,329680.0,0.0,0.0,0.0,-0.004686,77900.0
9656,2022-11-02,10.61,10.63,10.68,10.48,10.67,130298818.0,1.377816e+09,11.74,9.60,...,258900.0,833800.0,474700.0,269980.0,368800.0,192900.0,402500.0,178200.0,-0.003749,78320.0